name: Deploy to VPS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            export GIT_SSH_COMMAND="ssh -i ~/.ssh/github_deploy -o StrictHostKeyChecking=no"
            cd /var/www/smart4k
            git config --global --add safe.directory /var/www/smart4k
            git remote set-url origin git@github.com:yenesim/smart4k.git
            git fetch origin main
            git reset --hard origin/main
            npm install
            npm run build
            pm2 restart smart4k || pm2 start npm --name "smart4k" -- start
